language: python

python:
 - "3.5"
 - "3.6"

install:
 - pip install codecov coverage isort flake8 twine

script:
 - if python -c "import sys; exit(not (sys.version >= '3.6'))"; then pip install black; black --check .; fi
 - flake8 --max-line-length=88 .
 - isort --recursive --check-only --diff setup.py textbisect tests
 - ./setup.py sdist bdist_wheel
 - twine check dist/*
 - coverage run --include="./*" --omit="*/tests/*","setup.py" ./setup.py test

after_success:
 - codecov
